from exceptions.semantic_exception import SemanticException
